spring.application.name=use-grafana
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.prometheus.enabled=true

logging.logstash.host=${LOGSTASH_HOST:logstash}
logging.logstash.port=${LOGSTASH_PORT:5000}